version: '3.8'

services:
  server:
    container_name: server
    hostname: server
    build:
      context: .
    networks:
      - app
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - mosquitto
  mongo:
    container_name: mongo
    user: '1000:1000'
    hostname: mongo
    # restart: always
    image: mongo:6
    volumes:
      - ./volumes/data/mongo:/data/db
    networks:
      - app
    ports:
      - 27017:27017

  mosquitto:
    container_name: mqtt
    hostname: mqtt
    networks:
      - app
    image: eclipse-mosquitto:2
    volumes:
      - ./volumes/etc/mqtt/config/:/mosquitto/config/
      - ./volumes/etc/mqtt/log/:/mosquitto/log/
      - ./volumes/data/mqtt:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001
networks:
  app:
    driver: bridge
